services:
  mongo:
    container_name: plataforma-cursos-db
    image: mongo:8
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    restart: always

  api:
    container_name: plataforma-cursos-api
    build: .
    environment:
      - DB_URL=mongodb://mongo:27017/plataforma
    ports:
      - "5011:5011"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

volumes:
  mongo-data: